CREATE TABLE operations_new (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), account_ref TEXT NOT NULL REFERENCES account_scopes(id), action_id TEXT REFERENCES action_items(id), kind TEXT NOT NULL CHECK(kind IN ('create','update','complete','upload','delete')), operation_key TEXT NOT NULL UNIQUE, plan TEXT NOT NULL CHECK(json_valid(plan)), state TEXT NOT NULL CHECK(state IN ('validated','executing','succeeded','failed_safe','outcome_unknown','created_unverified','uploaded_unverified','applied_unverified','cancelled')), paused INTEGER NOT NULL DEFAULT 0 CHECK(paused IN (0,1)), remote_id TEXT, result TEXT CHECK(result IS NULL OR json_valid(result)), attempt INTEGER NOT NULL DEFAULT 0, revision INTEGER NOT NULL DEFAULT 0, created_at REAL NOT NULL, checked_at REAL);
INSERT INTO operations_new SELECT * FROM operations;
DROP TABLE operations;
ALTER TABLE operations_new RENAME TO operations;
CREATE INDEX operation_state ON operations(state,paused,created_at);
CREATE INDEX operation_remote_history ON operations(account_ref,remote_id,state,kind,created_at);
CREATE TRIGGER operation_plan_insert AFTER INSERT ON operations BEGIN INSERT INTO operation_plan_versions(operation_id,plan_id,payload,created_at) VALUES (NEW.id,coalesce(json_extract(NEW.plan,'$.plan_id'),NEW.id),NEW.plan,unixepoch('subsec')); END;
CREATE TRIGGER operation_plan_replace AFTER UPDATE OF plan ON operations WHEN OLD.plan != NEW.plan BEGIN INSERT INTO operation_plan_versions(operation_id,plan_id,payload,created_at) VALUES (NEW.id,coalesce(json_extract(NEW.plan,'$.plan_id'),NEW.id),NEW.plan,unixepoch('subsec')); END;
CREATE TABLE delete_confirmations (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), account_ref TEXT NOT NULL REFERENCES account_scopes(id), instance_id TEXT NOT NULL, actor_key TEXT NOT NULL, session_key TEXT NOT NULL REFERENCES sessions(id), message_key TEXT NOT NULL, request_key TEXT NOT NULL, project_id TEXT NOT NULL, task_id TEXT NOT NULL, snapshot TEXT NOT NULL CHECK(json_valid(snapshot)), expires_at REAL NOT NULL, consumed_by TEXT REFERENCES operations(id), created_at REAL NOT NULL, UNIQUE(account_ref,instance_id,actor_key,session_key,message_key,request_key));
